export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Views: Record<string, never>;
    Functions: Record<string, never>;
    CompositeTypes: Record<string, never>;
    Enums: {
      approval_status: 'pending' | 'approved' | 'rejected' | 'expired';
      agent_run_status: 'queued' | 'running' | 'blocked' | 'review_needed' | 'approved' | 'completed' | 'failed';
      dashboard_event_type: 'health' | 'gym' | 'water' | 'supplement' | 'agent' | 'memory' | 'system' | 'project' | 'revenue';
    };
    Tables: {
      goals: { Row: UserRow & { title: string; area: string; status: string; target_date: string | null; metadata: Json; created_at: string }; Insert: PartialIdUser & { title: string; area?: string; status?: string; target_date?: string | null; metadata?: Json }; Update: Partial<PartialIdUser & { title: string; area: string; status: string; target_date: string | null; metadata: Json }> };
      daily_checkins: { Row: UserRow & { checkin_date: string; today_score: number | null; mood: number | null; energy: number | null; notes: string | null }; Insert: PartialIdUser & { checkin_date: string; today_score?: number | null; mood?: number | null; energy?: number | null; notes?: string | null }; Update: Partial<PartialIdUser> };
      water_logs: { Row: UserRow & { logged_at: string; ounces: number; source: string; context: Json }; Insert: PartialIdUser & { logged_at?: string; ounces: number; source?: string; context?: Json }; Update: Partial<PartialIdUser> };
      supplements: { Row: UserRow & { name: string; schedule_slot: string; dosage: string | null; inventory_count: number | null; low_threshold: number; active: boolean }; Insert: PartialIdUser & { name: string; schedule_slot: string; dosage?: string | null; inventory_count?: number | null; low_threshold?: number; active?: boolean }; Update: Partial<PartialIdUser> };
      supplement_logs: { Row: UserRow & { supplement_id: string; scheduled_for: string | null; taken_at: string | null; missed: boolean; notes: string | null }; Insert: PartialIdUser & { supplement_id: string; scheduled_for?: string | null; taken_at?: string | null; missed?: boolean; notes?: string | null }; Update: Partial<PartialIdUser> };
      gym_exercises: { Row: UserRow & { name: string; muscle_group: string | null; equipment: string | null; created_at: string }; Insert: PartialIdUser & { name: string; muscle_group?: string | null; equipment?: string | null }; Update: Partial<PartialIdUser> };
      gym_workouts: { Row: UserRow & { workout_at: string; gym_location: string | null; body_weight: number | null; notes: string | null }; Insert: PartialIdUser & { workout_at?: string; gym_location?: string | null; body_weight?: number | null; notes?: string | null }; Update: Partial<PartialIdUser> };
      gym_sets: { Row: UserRow & { workout_id: string; exercise_id: string | null; set_number: number; reps: number | null; weight: number | null; rpe: number | null; notes: string | null }; Insert: PartialIdUser & { workout_id: string; exercise_id?: string | null; set_number: number; reps?: number | null; weight?: number | null; rpe?: number | null; notes?: string | null }; Update: Partial<PartialIdUser> };
      body_weight_logs: { Row: UserRow & { logged_date: string; weight: number; notes: string | null }; Insert: PartialIdUser & { logged_date: string; weight: number; notes?: string | null }; Update: Partial<PartialIdUser> };
      progress_photos: { Row: UserRow & { storage_bucket: string; storage_path: string; taken_at: string; notes: string | null }; Insert: PartialIdUser & { storage_bucket?: string; storage_path: string; taken_at?: string; notes?: string | null }; Update: Partial<PartialIdUser> };
      garmin_daily_summaries: { Row: UserRow & { summary_date: string; steps: number | null; calories: number | null; resting_hr: number | null; body_battery: number | null; stress_avg: number | null; training_load: number | null; source_file: string | null }; Insert: PartialIdUser & { summary_date: string; steps?: number | null; calories?: number | null; resting_hr?: number | null; body_battery?: number | null; stress_avg?: number | null; training_load?: number | null; source_file?: string | null }; Update: Partial<PartialIdUser> };
      garmin_sleep_summaries: { Row: UserRow & { sleep_date: string; sleep_score: number | null; duration_minutes: number | null; deep_minutes: number | null; rem_minutes: number | null; awake_minutes: number | null; source_file: string | null }; Insert: PartialIdUser & { sleep_date: string; sleep_score?: number | null; duration_minutes?: number | null; deep_minutes?: number | null; rem_minutes?: number | null; awake_minutes?: number | null; source_file?: string | null }; Update: Partial<PartialIdUser> };
      garmin_activities: { Row: UserRow & { activity_at: string; activity_type: string; duration_seconds: number | null; distance_meters: number | null; calories: number | null; avg_hr: number | null; training_effect: number | null; source_file: string | null }; Insert: PartialIdUser & { activity_at: string; activity_type: string; duration_seconds?: number | null; distance_meters?: number | null; calories?: number | null; avg_hr?: number | null; training_effect?: number | null; source_file?: string | null }; Update: Partial<PartialIdUser> };
      garmin_hrv: { Row: UserRow & { measured_date: string; overnight_avg: number | null; seven_day_avg: number | null; source_file: string | null }; Insert: PartialIdUser & { measured_date: string; overnight_avg?: number | null; seven_day_avg?: number | null; source_file?: string | null }; Update: Partial<PartialIdUser> };
      garmin_stress: { Row: UserRow & { measured_at: string; stress_level: number | null; duration_minutes: number | null; source_file: string | null }; Insert: PartialIdUser & { measured_at: string; stress_level?: number | null; duration_minutes?: number | null; source_file?: string | null }; Update: Partial<PartialIdUser> };
      agent_runs: { Row: UserRow & { provider: string; title: string; repo: string | null; status: Database['public']['Enums']['agent_run_status']; github_issue_url: string | null; github_pr_url: string | null; payload: Json; created_at: string }; Insert: PartialIdUser & { provider: string; title: string; repo?: string | null; status?: Database['public']['Enums']['agent_run_status']; github_issue_url?: string | null; github_pr_url?: string | null; payload?: Json }; Update: Partial<PartialIdUser> };
      agent_actions: { Row: UserRow & { run_id: string; action_type: string; status: string; command_preview: string | null; created_at: string }; Insert: PartialIdUser & { run_id: string; action_type: string; status?: string; command_preview?: string | null }; Update: Partial<PartialIdUser> };
      agent_approvals: { Row: UserRow & { action_id: string; status: Database['public']['Enums']['approval_status']; approved_by: string | null; decided_at: string | null; notes: string | null }; Insert: PartialIdUser & { action_id: string; status?: Database['public']['Enums']['approval_status']; approved_by?: string | null; decided_at?: string | null; notes?: string | null }; Update: Partial<PartialIdUser> };
      obsidian_notes: { Row: UserRow & { vault: string; path: string; title: string; body: string | null; tags: string[]; updated_at: string }; Insert: PartialIdUser & { vault: string; path: string; title: string; body?: string | null; tags?: string[]; updated_at?: string }; Update: Partial<PartialIdUser> };
      memory_chunks: { Row: UserRow & { note_id: string | null; chunk_text: string; embedding_ref: string | null; metadata: Json; created_at: string }; Insert: PartialIdUser & { note_id?: string | null; chunk_text: string; embedding_ref?: string | null; metadata?: Json }; Update: Partial<PartialIdUser> };
      vps_hosts: { Row: UserRow & { name: string; provider: string; hostname: string | null; labels: string[]; active: boolean }; Insert: PartialIdUser & { name: string; provider?: string; hostname?: string | null; labels?: string[]; active?: boolean }; Update: Partial<PartialIdUser> };
      vps_metrics: { Row: UserRow & { host_id: string; captured_at: string; cpu_percent: number | null; ram_percent: number | null; disk_percent: number | null; service_status: Json; model_list: string[] }; Insert: PartialIdUser & { host_id: string; captured_at?: string; cpu_percent?: number | null; ram_percent?: number | null; disk_percent?: number | null; service_status?: Json; model_list?: string[] }; Update: Partial<PartialIdUser> };
      projects: { Row: UserRow & { name: string; status: string; revenue_target: number | null; metadata: Json; created_at: string }; Insert: PartialIdUser & { name: string; status?: string; revenue_target?: number | null; metadata?: Json }; Update: Partial<PartialIdUser> };
      project_tasks: { Row: UserRow & { project_id: string; title: string; status: string; due_at: string | null; completed_at: string | null }; Insert: PartialIdUser & { project_id: string; title: string; status?: string; due_at?: string | null; completed_at?: string | null }; Update: Partial<PartialIdUser> };
      revenue_events: { Row: UserRow & { project_id: string | null; occurred_at: string; amount: number; currency: string; source: string; metadata: Json }; Insert: PartialIdUser & { project_id?: string | null; occurred_at?: string; amount: number; currency?: string; source: string; metadata?: Json }; Update: Partial<PartialIdUser> };
      dashboard_events: { Row: UserRow & { event_type: Database['public']['Enums']['dashboard_event_type']; title: string; payload: Json; created_at: string }; Insert: PartialIdUser & { event_type: Database['public']['Enums']['dashboard_event_type']; title: string; payload?: Json }; Update: Partial<PartialIdUser> };
    };
  };
};

type UserRow = { id: string; user_id: string };
type PartialIdUser = { id?: string; user_id: string };
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
