-- GarrettOS Phase 1 Supabase draft migration.
-- Security posture: every data table is user-scoped and RLS is enabled.
create extension if not exists pgcrypto;

create type approval_status as enum ('pending','approved','rejected','expired');
create type agent_run_status as enum ('queued','running','blocked','review_needed','approved','completed','failed');
create type dashboard_event_type as enum ('health','gym','water','supplement','agent','memory','system','project','revenue');

create table goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, area text not null default 'general', status text not null default 'active', target_date date, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table daily_checkins (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, checkin_date date not null, today_score int check (today_score between 0 and 100), mood int check (mood between 1 and 10), energy int check (energy between 1 and 10), notes text, unique(user_id, checkin_date));
create table water_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, logged_at timestamptz not null default now(), ounces numeric(6,2) not null check (ounces > 0), source text not null default 'manual', context jsonb not null default '{}'::jsonb);
create table supplements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, schedule_slot text not null, dosage text, inventory_count numeric(8,2), low_threshold numeric(8,2) not null default 7, active boolean not null default true);
create table supplement_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, supplement_id uuid not null references supplements(id) on delete cascade, scheduled_for timestamptz, taken_at timestamptz, missed boolean not null default false, notes text);
create table gym_exercises (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, muscle_group text, equipment text, created_at timestamptz not null default now());
create table gym_workouts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_at timestamptz not null default now(), gym_location text, body_weight numeric(6,2), notes text);
create table gym_sets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_id uuid not null references gym_workouts(id) on delete cascade, exercise_id uuid references gym_exercises(id), set_number int not null, reps int, weight numeric(8,2), rpe numeric(3,1), notes text);
create table body_weight_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, logged_date date not null, weight numeric(6,2) not null, notes text, unique(user_id, logged_date));
create table progress_photos (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, storage_bucket text not null default 'progress-photos', storage_path text not null, taken_at timestamptz not null default now(), notes text);
create table garmin_daily_summaries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, summary_date date not null, steps int, calories int, resting_hr int, body_battery int, stress_avg int, training_load numeric(8,2), source_file text, unique(user_id, summary_date));
create table garmin_sleep_summaries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, sleep_date date not null, sleep_score int, duration_minutes int, deep_minutes int, rem_minutes int, awake_minutes int, source_file text, unique(user_id, sleep_date));
create table garmin_activities (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, activity_at timestamptz not null, activity_type text not null, duration_seconds int, distance_meters numeric(10,2), calories int, avg_hr int, training_effect numeric(3,1), source_file text);
create table garmin_hrv (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, measured_date date not null, overnight_avg numeric(6,2), seven_day_avg numeric(6,2), source_file text, unique(user_id, measured_date));
create table garmin_stress (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, measured_at timestamptz not null, stress_level int check (stress_level between 0 and 100), duration_minutes int, source_file text);
create table agent_runs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, provider text not null, title text not null, repo text, status agent_run_status not null default 'queued', github_issue_url text, github_pr_url text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table agent_actions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, run_id uuid not null references agent_runs(id) on delete cascade, action_type text not null, status text not null default 'proposed', command_preview text, created_at timestamptz not null default now());
create table agent_approvals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, action_id uuid not null references agent_actions(id) on delete cascade, status approval_status not null default 'pending', approved_by uuid references auth.users(id), decided_at timestamptz, notes text);
create table obsidian_notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, vault text not null, path text not null, title text not null, body text, tags text[] not null default '{}', updated_at timestamptz not null default now(), unique(user_id, vault, path));
create table memory_chunks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, note_id uuid references obsidian_notes(id) on delete cascade, chunk_text text not null, embedding_ref text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table vps_hosts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, provider text not null default 'hetzner', hostname text, labels text[] not null default '{}', active boolean not null default true);
create table vps_metrics (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, host_id uuid not null references vps_hosts(id) on delete cascade, captured_at timestamptz not null default now(), cpu_percent numeric(5,2), ram_percent numeric(5,2), disk_percent numeric(5,2), service_status jsonb not null default '{}'::jsonb, model_list text[] not null default '{}');
create table projects (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, status text not null default 'active', revenue_target numeric(12,2), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table project_tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references projects(id) on delete cascade, title text not null, status text not null default 'todo', due_at timestamptz, completed_at timestamptz);
create table revenue_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid references projects(id) on delete set null, occurred_at timestamptz not null default now(), amount numeric(12,2) not null, currency text not null default 'USD', source text not null, metadata jsonb not null default '{}'::jsonb);
create table dashboard_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_type dashboard_event_type not null, title text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

alter table goals enable row level security; alter table daily_checkins enable row level security; alter table water_logs enable row level security; alter table supplements enable row level security; alter table supplement_logs enable row level security; alter table gym_exercises enable row level security; alter table gym_workouts enable row level security; alter table gym_sets enable row level security; alter table body_weight_logs enable row level security; alter table progress_photos enable row level security; alter table garmin_daily_summaries enable row level security; alter table garmin_sleep_summaries enable row level security; alter table garmin_activities enable row level security; alter table garmin_hrv enable row level security; alter table garmin_stress enable row level security; alter table agent_runs enable row level security; alter table agent_actions enable row level security; alter table agent_approvals enable row level security; alter table obsidian_notes enable row level security; alter table memory_chunks enable row level security; alter table vps_hosts enable row level security; alter table vps_metrics enable row level security; alter table projects enable row level security; alter table project_tasks enable row level security; alter table revenue_events enable row level security; alter table dashboard_events enable row level security;

-- Draft policy pattern: generate one owner-only policy per table in production migrations.
-- Example:
create policy "goals are user scoped" on goals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "agent approvals are user scoped" on agent_approvals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
